# Your item's name the player will see. It can contain color codes for colored names.
DisplayName: 175 TPS
# Your item's lore (tooltip description), see the default values for examples to what can be used
# Each '-' represents a new line.
Lore: 
- un poco mejor, pero la siguiente si esta potente
# The amount of training points to give the player.
Amount: 175
# Whether the item should be owned by a player or not. false by default.
SoulBound: false
# How many seconds should the item be unusable after use. Default value is 1 second.
Cooldown: 1
