MenusActivityText: Playing with Customforms!
SinglePlayer:
    UpperActivityText: Playing with Customforms!
    BottomActivityText: Playing on my awesome singleplayer world
Multiplayer:
    UpperActivityText: Playing with Customforms!
    BottomActivityText: Playing on my awesome server
