# Your item's name the player will see. It can contain color codes for colored names.
DisplayName: My PU Item
# Your item's lore (tooltip description), see the default values for examples to what can be used
# Each '-' represents a new line.
Lore: 
- ThisIsLoreWithoutSpaces
- This is lore with spaces
- \u00A7bThis is color coded lore
# An option to set if the player will receive different amount of stats in each stat. false by default.
uniqueStatAmount: false
# The amount of stat points the player will get for each stat type.
StatAmount:
    jrmcIntI: 6
    jrmcWilI: 7
    jrmcDexI: 9
    jrmcCnsI: 8
    jrmcCncI: 5
    jrmcStrI: 10
# The amount of stats to give the player. Only applies when UniqueStatAmount is set to false.
Amount: 10
# Whether the itme should be owned by a player or not. false by default.
SoulBound: false
# How many seconds should the item be unusable after use. Default value is 1 second.
Cooldown: 1
